
import { Footer, Header } from '@/components'
import './globals.css'


export const metadata = {
  title: 'Shoe Shop',
  description: 'Generated by devkingsley',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
